# Generated by Django 5.2.16 on 2026-08-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
