# Generated by Django 5.2.16 on 2026-08-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('delivery_radius_km', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('support_email', models.EmailField(default='support@rayalseema.local', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_settings',
            },
        ),
    ]
