# Generated by Django 5.2.16 on 2026-08-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant_response',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
